services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    # volumes:
    # - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-container
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: .
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
      - LISTENING_PORT=5000
    volumes:
      - /app/node_modules
      - .:/app
    ports:
      - '5000'
